[font]
size = 6

[font.bold]
family = "HackNerdFont"
style = "Bold"

[font.bold_italic]
family = "HackNerdFont"
style = "Regular"

[font.italic]
family = "HackNerdFont"
style = "Italic"

[font.normal]
family = "HackNerdFont"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Control|Shift"

[window]
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 2
y = 2
